### ISSUE TITLE
To open a pull request 

### ISSUE THREAD

**Issue by RanaAlqrenawi** [TR-SUNSHINE/Static-Frontend#1]
It's important to make sure we don't individually merge any changes to the "main" branch without we **_open a pull request_** for that. 

Ideally, the one who's done the commit will _open a pull reques_t and make sure to _assign the team._ Two of the team's members will have to review it, write their comments and _the last one can just merge and delete the branche_.

Let's make sure to practise this as we go. @Chenerywoman @devagx @thurschm2

**Comment by devagx** [comment]
can this issue be closed now? ive document the process in the git hub document
