### ISSUE TITLE
Weekly Project Review with TR

### ISSUE THREAD

**Issue by RanaAlqrenawi** [TR-SUNSHINE/Static-Frontend#14]
This is our place to arrange for our weekly check-ins with the TR team moving on so we are sure of the points we want to present and how to run the meeting for the best using of time.

**Comment by Chenerywoman** [comment]
HI Rana - Do you mean put the points we want to raise with TR here? (I assume you don't mean actually arrange the time of the meeting and Zoom link etc) We can discuss as a team and you can explain to us on Monday :-) Thanks!

**Comment by RanaAlqrenawi** [comment]
@Chenerywoman well, yes. I mean to make sure we have clear points to talk about and what to share, plus trying to get more benefit out of these meetings something like advice on a piece of work or a question or any kind of help.

**Comment by Chenerywoman** [comment]
Yes, I agree.  I am also thinking about putting some of my questions on Slack for everyone to see in case it benefits the other team and also give the tutors time to prepare.   Also, I think our questions need to go into an agenda for meeting with the tutors, so we don't forget to ask any.

**Comment by Chenerywoman** [comment]
@RanaAlqrenawi shall we also close this one as we are agreed to have questions for the tutors
