### ISSUE TITLE
My Walks page - add titles as per prototype

### ISSUE THREAD

**Issue by Chenerywoman** [TR-SUNSHINE/Static-Frontend#16]
Please could the my walks page have the headings for the walk name and rating, so as to be consistent with the prototype as agreed #and any suggested changes be suggested during meeting(s) to discuss look of the project. 
![Screenshot 2021-02-18 at 12 26 28](https://user-images.githubusercontent.com/23318608/108356847-8ef78380-71e4-11eb-9c7a-20beff60510b.png)

**Comment by RanaAlqrenawi** [comment]
So, I am having the **headings back** and I am removing the trips' reviews' count. I was just thinking it's a good way to give this information to the user .. but extra backend work so I have removed that.

**a quick question:** are we presenting an ave of something for the user regarding the walks rating? I think it's the user choose to rate from **1 to 5** and this is what we present without calculating any ave. What do you think?

On the final shape, I do think from the UX side the font of the heading is a bit annoying and the box as it is is not very friendly. Having this approach in the attached photo for us to finalise the discussion of the layout of this page.

**_Just a hint_**, as we are all in a learning process, not having a design team and UX expert so we as developers stick to what they say, **_then it's good to keep a room for improvements as we are going._**

Thanks.

Thoughts? @devagx @Chenerywoman @thurschm2 

<img width="294" alt="Screenshot 2021-02-18 at 13 07 31" src="https://user-images.githubusercontent.com/15797574/108361984-134d0500-71eb-11eb-91ad-ca5e1e833524.png">

**Comment by devagx** [comment]
Rana - regarding rating. I have a 5 star rating option on my individual walks page. So I think the rating should be stars 1 to 5. So I guess we should align here on the styling etc. But looking at yours above, its looking like mine anyway

**Comment by Chenerywoman** [comment]
I like the version without the box too.  I am really feeling my lack of design experience :-) .  I think it is better with the headings though as it is clearer to the user what they are.  I think the plan, in line with the user story is to "rate my satisfaction with a walk **over time** , which is why if we can do it, we can do an average rating for each walk i.e. the average  score out of five of all the times a user has rated a walk.  So the title would need to be 'Average Rating' to make that clear.  On the individual walk page, there is a chart/graph showing the changes to walker satisfaction with a walk over time (in the prototype & Alun has linked in a chart into the static version.

**Comment by Chenerywoman** [comment]
Closing issue as moving to React version & repository & titles now on the page (will need to agree re. title to be Walk rating v Average Rating once got backend data & manipulated it to display on screen)
