### ISSUE TITLE
Link the pages together

### ISSUE THREAD

**Issue by RanaAlqrenawi** [TR-SUNSHINE/Static-Frontend#17]
We need to link the pages together on the **navigation** we have agreed on earlier {**prototype**}. We also need to make sure we have the **same header and footer on each page + the menu on the side**. Will the **frontend team** be ok with setting up that for the project and we implement it in our pages or do we need to agree on who to work on what for the final layout consistency?

Thanks.

**Comment by Chenerywoman** [comment]
Hi Rana.  Agree this needs doing, but we ran out of time this week.  We will need to discuss in our Sprint Planning on Monday - we have already started discussing.   Each of them will be a separate component in React- header, footer, navbar.  There are lots of components to create (I will prepare a list for Monday) so we can allocate them all between us in the Sprint Planning meeting.

**Comment by Chenerywoman** [comment]
@RanaAlqrenawi  I am closing this as we are moving on to the React version.  Hope that's ok.
